### ISSUE TITLE
term.asm:28: error: expecting `)'

### ISSUE THREAD

**Issue by ghost** [NikitaIvanovV/snake-asm#1]
On building I get this error,

```
nasm -o build/term.o -felf64 term.asm
term.asm:28: error: expecting `)'
term.asm:29: error: expecting `)'
make: *** [Makefile:21: build/term.o] Error 1
```

```
Ubuntu 20.04.3 LTS x86_64
NASM version 2.14.02
```

**Comment by NikitaIvanovV** [comment]
I used NASM 2.15 to make the game. Could you try removing the parentheses on these lines? Not sure if it will still be correct syntax but worth a try.

```nasm
and dword [tty+termios_s.flags], (~ICANON)
and dword [tty+termios_s.flags], (~ECHO)
```

**Comment by ghost** [comment]
```
nasm -o build/term.o -felf64 term.asm
term.asm:28: error: comma, colon, decorator or end of line expected after operand
term.asm:29: error: comma, colon, decorator or end of line expected after operand
make: *** [Makefile:21: build/term.o] Error 1
```

It gives this error on removing parentheses.

**Comment by windowz414** [comment]
I tried to build just now too, got the same error.

```
windowzytch@android-dev:~/snake-asm$ make
nasm -o build/print.o -felf64 print.asm
nasm -o build/snake.o -felf64 snake.asm
nasm -o build/syscall.o -felf64 syscall.asm
nasm -o build/term.o -felf64 term.asm
term.asm:28: error: expecting `)'
term.asm:29: error: expecting `)'
make: *** [Makefile:21: build/term.o] Error 1
```

In case you wonder, I have NASM 2.14.02, installed from Ubuntu APT
repos and Ubuntu 20.04.3 LTS, running on Linux 5.17.0-rc3.

**Comment by NikitaIvanovV** [comment]
Could you guys try to replace 3rd and 4th lines with this?
```asm
%define ICANON (1<<1)
%define ECHO   (1<<3)
```
If it doesn't work, try removing parentheses.

**Comment by ghost** [comment]
Thanks, that solves the issue.

**Comment by windowz414** [comment]
> Could you guys try to replace 3rd and 4th lines with this?
> 
> ```assembly
> %define ICANON (1<<1)
> %define ECHO   (1<<3)
> ```
> 
> If it doesn't work, try removing parentheses.

Yup, all fine. Thanks!

**Comment by NikitaIvanovV** [comment]
Awesome! I've added the fix to the master branch. Thank you for reporting the problem guys!

**Comment by windowz414** [comment]
> Awesome! I've added the fix to the master branch. Thank you for reporting the problem guys!

Any time! I installed this on my Android build server and it's of course pretty good to open a new window in `tmux` and pull up a Snake game when we're bored. :P
